### PR TITLE
New style of gallery where the photo switch is right in place. 

### PR DESCRIPTION
**Pull request by signalwerk**
Check here for an example;
http://mygarden.ch/schaugarten/schaugarten.html

There is no other need than jquery.

### CODE REVIEW

**Comment by daniellienert** [comment]
hey @signalwerk, 
Thanks a lot for your contribution. Great to see, that the theme concept works out!
But I'am really sorry - I don't like to add more themes to the gallery (IMHO, the existing two are already one to much), in order to keep the base package slim.
It would be great if you publish your own package containing the new theme. If you need any help doing this, let me know.

Cheers,
Daniel

**Comment by signalwerk** [comment]
Do you really think it's a good idea to have all the packages with only small changes in new packages? For me that would mean that we all spend our power to divert from each other and not keep our forces together. I don't say it's a good idea to have n themes in your package. But I think it would be good to cover as many cases as possible. I like for example the fact that I can turn off the JS or CSS in your package a lot. Then I can just bring in my code but for DOM-Stuff I need the code from the Plugin.

**Comment by daniellienert** [comment]
Hey @signalwerk,
ah, I assume there is a misunderstanding. It would be a bad thing, if you would fork the gallery package and add your changes there - if that is, what you understood I was proposing.

I propose, you start a new package called e.g. `signalwerk/inplace-gallery-theme` , which requires `dl-gallery`and just put the code of this PR there. That would mean, no code duplication and also not overloading the dl-gallery package with themes for every purpose. And composer does the magic.

I am convinced that this is the better approach - I tried to have the All-Themes-In-One approach for my TYPO3-gallery, and that didn't work out.

Cheers,
Daniel

**Comment by daniellienert** [comment]
Hey @signalwerk, 
now I also had the need to build an own gallery theme for a customer project and realized that there some blockers like hard coded Package names and stuff. 
I refactored everything to fusion components, which should make it pretty easy to build an own package with a theme bases on the gallery.

Cheers,
Daniel

**Pull request closed without merging**
