### PR TITLE
[TASK] Declare compatibility with Neos 8.0

### PR DESCRIPTION
**Pull request by soee**

### CODE REVIEW

**Comment by crydotsnake** [comment]
Tested it, and its working great with Neos 8 !

**Comment by JulienFourel** [comment]
Waiting for Neos 8 compatibility ! :)

**Comment by lorenzulrich** [comment]
@daniellienert Any chance to get this merged?

**Comment by daniellienert** [comment]
@lorenzulrich - absolutely! Sorry for the delay.

**Comment by lorenzulrich** [comment]
@daniellienert Thanks a lot!

**Pull request merged**
